[package]
name = "shotcaller"
version = "0.1.0"
authors = ["Joël Lupien (Jojolepro) <jojolepro@jojolepro.com>"]
edition = "2018"

[dependencies]
#minigene = { path = "../minigene" }
minigene = { git = "https://github.com/jojolepro/minigene" }
